version: 0.0
os: linux
files:
    - source: /
      destination: /home/api/api_back
    - source: /nginx
      destination: /opt/codedeploy-agent/deployment-root/06d913c2-b77e-41b4-8589-d966e21ebdf9/d-FK6FGC47K/deployment-archive/nginx
    - source: /docker-compose.yml
      destination: /home/api
    - source: /.env
      destination: /home/api
    - source: /config/
      destination: /home/api/config
file_exists_behavior: OVERWRITE

permissions:
    - object: /home/api
      pattern: '**'
      owner: root
      group: root

hooks:
    AfterInstall:
        - location: scripts/after-deploy.sh
          timeout: 2000
          runas: root